# Generated by Django 3.1.5 on 2021-07-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='foto')),
                ('nome', models.CharField(max_length=75, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='endereço de email')),
            ],
        ),
    ]
